### ISSUE TITLE
setup auth

### ISSUE THREAD

**Issue by deolivtiago** [deolivtiago/api#5]
# description

add auth to protect users route and add public routes for sign up and sign in

## linked issues

- [x] include guardian to handle jwt auth
- [x] setup authentication with access token
- [x] add auth protection to users route
- [x] add public routes for sign in and sign up
